<?
$arTooltips = array(
	"PATH_TO_ORDER" => GetMessage("PATH_TO_ORDER_TIP"),
	"HIDE_COUPON" => GetMessage("HIDE_COUPON_TIP"),
	"COLUMNS_LIST" => GetMessage("COLUMNS_LIST_TIP"),
	"SET_TITLE" => GetMessage("SET_TITLE_TIP"),
	"QUANTITY_FLOAT" => GetMessage("QUANTITY_FLOAT_TIP"),
	"PRICE_VAT_INCLUDE" => GetMessage("PRICE_VAT_INCLUDE_TIP"),
	"PRICE_VAT_SHOW_VALUE" => GetMessage("PRICE_VAT_SHOW_VALUE_TIP"),
	"PRICE_TAX_SHOW_VALUE" => GetMessage("PRICE_TAX_SHOW_VALUE_TIP"),
);
?>